public class EmailTriggerClass {
    /* public static void sendEmailNotification(List<Contact> conList)
    {
        List<Messaging.Email> emailList = new List<Messaging.Email>();
        for(Contact con : conList)
        {
            if(con.Email != null)
            {
                Messaging.SingleEmailMessage emailMsg = new Messaging.SingleEmailMessage();
                String[] toAddress = new String[]{con.Email};
                emailMsg.setToAddresses(toAddress);
                String emailSub = 
            }
        }
    } */
}